name: schaukelaktuatorapp
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">3.0.0"

dependencies:
  # charts_flutter: ^0.12.0
  eventify: ^1.0.1
  fl_chart: ^0.70.0
  flutter:
    sdk: flutter
  http: ^1.2.2
  mic_stream: ^0.7.1+2
  web_socket_channel: ^3.0.1
  # cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  

flutter:
  uses-material-design: true
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
